# expose mysql only inside cluster
# be connects to mysql via service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysqldb
  ports:
    - port: 3306
      targetPort: 3306